from pathlib import Path

p = Path('stem_dsp.cpp')
s = p.read_text(encoding='utf-8')

old = '''constexpr double kPrefetchSeconds = 20.0;\nconstexpr double kSwitchFadeSeconds = 0.050;\n'''
new = '''constexpr double kPrefetchSeconds = 20.0;\n// Original PCM is cheap to decode, so keep a smaller trigger margin around the\n// playhead continuously. This makes the very first platter grab audible instead\n// of waiting for a transport request after the mouse is already down.\nconstexpr double kOriginalPrefetchSeconds = 5.0;\nconstexpr double kSwitchFadeSeconds = 0.050;\n'''
if old not in s:
    raise SystemExit('prefetch constant anchor not found')
s = s.replace(old, new, 1)

old = '''        if (!m_path.empty() &&\n            stemmode::get() !=\n                stemmode::mode::original) {\n\n            queue_job_locked(0.0, true);\n        }\n\n        m_cv.notify_one();\n'''
new = '''        if (!m_path.empty()) {\n            const stemmode::mode mode = stemmode::get();\n            if (mode != stemmode::mode::original) {\n                queue_job_locked(0.0, true);\n            } else {\n                // Pre-decode the first Original transport window immediately.\n                // Unlike stem caching this is just Media Foundation decode and is\n                // cheap enough to keep ready for platter work all the time.\n                m_jobs.emplace_back(cache_job{\n                    m_generation, m_path, 0.0, true, false, false});\n                m_job_pending = true;\n            }\n        }\n\n        m_cv.notify_one();\n'''
if old not in s:
    raise SystemExit('new_track cache anchor not found')
s = s.replace(old, new, 1)

old = '''    void ensure_ahead(double playback_seconds) {\n        if (stemmode::get() ==\n            stemmode::mode::original) {\n            return;\n        }\n\n        std::lock_guard<std::mutex> lock(\n            m_mutex);\n\n        if (m_path.empty() ||\n            m_job_pending) {\n            return;\n        }\n\n        double cache_end = -1.0;\n\n        if (!m_segments.empty()) {\n            cache_end =\n                m_segments.back()->end_seconds;\n        }\n\n        // No cache at all: begin at the current playback position.\n        if (cache_end < 0.0) {\n            queue_job_locked(\n                playback_seconds);\n\n            m_cv.notify_one();\n            return;\n        }\n\n        if (cache_end -\n                playback_seconds <=\n            kPrefetchSeconds) {\n\n            double next =\n                cache_end -\n                kCacheOverlapSeconds;\n\n            if (next < playback_seconds) {\n                next = playback_seconds;\n            }\n\n            queue_job_locked(next);\n            m_cv.notify_one();\n        }\n    }\n'''
new = '''    void ensure_ahead(double playback_seconds) {\n        const stemmode::mode mode = stemmode::get();\n\n        std::lock_guard<std::mutex> lock(\n            m_mutex);\n\n        if (m_path.empty() ||\n            m_job_pending) {\n            return;\n        }\n\n        if (mode == stemmode::mode::original) {\n            // Find Original PCM that actually covers the playhead. Completed\n            // windows are retained, so this also gives scratch useful history.\n            double covering_end = -1.0;\n            for (const auto& seg_ptr : m_segments) {\n                const cache_segment& seg = *seg_ptr;\n                if (!segment_has_mode(seg, mode)) continue;\n                if (playback_seconds >= seg.start_seconds - 1.0e-6 &&\n                    playback_seconds < seg.end_seconds) {\n                    covering_end = (std::max)(covering_end, seg.end_seconds);\n                }\n            }\n\n            double next = 0.0;\n            if (covering_end < 0.0) {\n                // A seek/jump landed outside cached Original PCM. Center a fresh\n                // 20-second window so both scratch directions become available.\n                next = (std::max)(\n                    0.0, playback_seconds - kCacheSeconds * 0.5);\n            } else if (covering_end - playback_seconds <=\n                       kOriginalPrefetchSeconds) {\n                // Extend ahead with the normal overlap before the playhead reaches\n                // the current window edge.\n                next = (std::max)(\n                    0.0, covering_end - kCacheOverlapSeconds);\n            } else {\n                return;\n            }\n\n            m_jobs.emplace_back(cache_job{\n                m_generation, m_path, next, true, false, false});\n            m_job_pending = true;\n            m_cv.notify_one();\n            return;\n        }\n\n        double cache_end = -1.0;\n\n        if (!m_segments.empty()) {\n            cache_end =\n                m_segments.back()->end_seconds;\n        }\n\n        // No cache at all: begin at the current playback position.\n        if (cache_end < 0.0) {\n            queue_job_locked(\n                playback_seconds);\n\n            m_cv.notify_one();\n            return;\n        }\n\n        if (cache_end -\n                playback_seconds <=\n            kPrefetchSeconds) {\n\n            double next =\n                cache_end -\n                kCacheOverlapSeconds;\n\n            if (next < playback_seconds) {\n                next = playback_seconds;\n            }\n\n            queue_job_locked(next);\n            m_cv.notify_one();\n        }\n    }\n'''
if old not in s:
    raise SystemExit('ensure_ahead anchor not found')
s = s.replace(old, new, 1)

p.write_text(s, encoding='utf-8')
print('patched continuous Original transport prefetch')
