from pathlib import Path

p = Path('stem_dsp.cpp')
s = p.read_text(encoding='utf-8')

def rep(old, new):
    global s
    if old not in s:
        raise SystemExit('anchor not found:\n' + old[:300])
    s = s.replace(old, new, 1)

rep('''std::wstring local_path_from_metadb(\n    metadb_handle_ptr handle) {\n\n    if (handle.is_empty()) return {};\n\n    std::wstring path =\n        utf8_to_wide_cache(\n            handle->get_path());\n\n    const std::wstring prefix =\n        L"file://";\n\n    if (path.rfind(prefix, 0) == 0) {\n        path.erase(0, prefix.size());\n    }\n\n    return path;\n}\n\nstruct cache_segment {\n''', '''std::wstring local_path_from_metadb(\n    metadb_handle_ptr handle) {\n\n    if (handle.is_empty()) return {};\n\n    std::wstring path =\n        utf8_to_wide_cache(\n            handle->get_path());\n\n    const std::wstring prefix =\n        L"file://";\n\n    if (path.rfind(prefix, 0) == 0) {\n        path.erase(0, prefix.size());\n    }\n\n    return path;\n}\n\nstd::wstring local_path_from_utf8_cache(const char* raw) {\n    std::wstring path = utf8_to_wide_cache(raw);\n    const std::wstring prefix = L"file://";\n    if (path.rfind(prefix, 0) == 0) path.erase(0, prefix.size());\n    return path;\n}\n\nbool convert_to_cache_stereo(\n    const float* input,\n    size_t frames,\n    unsigned channels,\n    unsigned sample_rate,\n    std::vector<float>& out) {\n\n    out.clear();\n    if (input == nullptr || frames == 0 || channels == 0 || sample_rate == 0) return false;\n\n    size_t output_frames = frames;\n    if (sample_rate != kCacheRate) {\n        output_frames = (std::max)(\n            static_cast<size_t>(1),\n            static_cast<size_t>(std::llround(\n                static_cast<double>(frames) *\n                static_cast<double>(kCacheRate) /\n                static_cast<double>(sample_rate))));\n    }\n\n    out.assign(output_frames * kCacheChannels, 0.0f);\n\n    auto read_channel = [input, channels, frames](size_t frame, unsigned ch) -> float {\n        frame = (std::min)(frame, frames - 1);\n        const float* src = input + frame * channels;\n        if (channels == 1) return src[0];\n        return src[ch == 0 ? 0 : 1];\n    };\n\n    if (frames == 1 || output_frames == 1) {\n        const float l = read_channel(0, 0);\n        const float r = read_channel(0, 1);\n        for (size_t i = 0; i < output_frames; ++i) {\n            out[i * 2] = l;\n            out[i * 2 + 1] = r;\n        }\n        return true;\n    }\n\n    const double scale = static_cast<double>(frames - 1) /\n        static_cast<double>(output_frames - 1);\n\n    for (size_t i = 0; i < output_frames; ++i) {\n        const double source = static_cast<double>(i) * scale;\n        const size_t i0 = static_cast<size_t>(source);\n        const size_t i1 = (std::min)(i0 + 1, frames - 1);\n        const float frac = static_cast<float>(source - static_cast<double>(i0));\n        for (unsigned ch = 0; ch < 2; ++ch) {\n            const float a = read_channel(i0, ch);\n            const float b = read_channel(i1, ch);\n            out[i * 2 + ch] = a + (b - a) * frac;\n        }\n    }\n    return true;\n}\n\nstruct cache_segment {\n''')

rep('''    std::vector<float> original;\n    std::vector<float> vocals;\n    std::vector<float> instrumental;\n};\n''', '''    std::vector<float> original;\n    std::vector<float> vocals;\n    std::vector<float> instrumental;\n\n    // True when this PCM was produced by Spectral Waveform's contextual stem\n    // analysis. These blocks are preferred for jog/reverse so we never pay a\n    // second Spleeter pass for an already processed visible region.\n    bool external_waveform = false;\n};\n''')

rep('''    bool transport_position_ready(double position_seconds) const {\n''', '''    bool publish_external_segment(\n        const std::wstring& path,\n        double start_seconds,\n        const float* original,\n        const float* vocals,\n        const float* instrumental,\n        size_t frames,\n        unsigned channels,\n        unsigned sample_rate) {\n\n        if (path.empty() || start_seconds < 0.0) return false;\n\n        std::vector<float> cache_original;\n        std::vector<float> cache_vocals;\n        std::vector<float> cache_instrumental;\n        if (!convert_to_cache_stereo(original, frames, channels, sample_rate, cache_original) ||\n            !convert_to_cache_stereo(vocals, frames, channels, sample_rate, cache_vocals) ||\n            !convert_to_cache_stereo(instrumental, frames, channels, sample_rate, cache_instrumental)) {\n            return false;\n        }\n        if (cache_original.empty() || cache_vocals.size() != cache_original.size() ||\n            cache_instrumental.size() != cache_original.size()) return false;\n\n        const size_t cache_frames = cache_original.size() / kCacheChannels;\n        if (cache_frames == 0) return false;\n        const double end_seconds = start_seconds +\n            static_cast<double>(cache_frames) / static_cast<double>(kCacheRate);\n\n        {\n            std::lock_guard<std::mutex> lock(m_mutex);\n            if (m_path.empty() || _wcsicmp(m_path.c_str(), path.c_str()) != 0) return false;\n\n            // A re-analysis can republish the same tile. Replace the previous\n            // external copy instead of growing the in-memory cache indefinitely.\n            for (auto it = m_segments.begin(); it != m_segments.end();) {\n                if (it->external_waveform &&\n                    std::abs(it->start_seconds - start_seconds) < 0.001 &&\n                    std::abs(it->end_seconds - end_seconds) < 0.003) {\n                    it = m_segments.erase(it);\n                } else {\n                    ++it;\n                }\n            }\n\n            cache_segment seg;\n            seg.generation = m_generation;\n            seg.start_seconds = start_seconds;\n            seg.end_seconds = end_seconds;\n            seg.original = std::move(cache_original);\n            seg.vocals = std::move(cache_vocals);\n            seg.instrumental = std::move(cache_instrumental);\n            seg.external_waveform = true;\n            m_segments.push_back(std::move(seg));\n        }\n\n        m_ready_cv.notify_all();\n        return true;\n    }\n\n    bool transport_position_ready(double position_seconds) const {\n''')

old = '''        for (const auto& seg : m_segments) {\n            if (!segment_has_mode(seg, mode)) continue;\n            if (seg.start_seconds <= need_start + 1.0e-6 &&\n                seg.end_seconds >= need_end - 1.0e-6) {\n                return;\n            }\n        }\n'''
new = '''        if (range_ready_locked(mode, need_start, need_end)) return;\n'''
rep(old, new)

old = '''            const cache_segment* first =\n                nullptr;\n\n            const cache_segment* second =\n                nullptr;\n\n            for (const auto& seg :\n                 snapshot) {\n\n                if (!segment_has_mode(seg, mode)) continue;\n\n                if (t >= seg.start_seconds &&\n                    t < seg.end_seconds) {\n\n                    if (!first) {\n                        first = &seg;\n                    }\n                    else {\n                        second = &seg;\n                        break;\n                    }\n                }\n            }\n\n            if (!first) {\n                return false;\n            }\n'''
new = '''            const cache_segment* first = nullptr;\n            const cache_segment* second = nullptr;\n\n            // Prefer the newest Spectral Waveform PCM tile. It already contains\n            // the contextual Spleeter result that produced the visible waveform,\n            // so using it avoids both duplicate inference and transport delay.\n            for (auto it = snapshot.rbegin(); it != snapshot.rend(); ++it) {\n                if (!it->external_waveform || !segment_has_mode(*it, mode)) continue;\n                if (t >= it->start_seconds && t < it->end_seconds) {\n                    first = &*it;\n                    break;\n                }\n            }\n\n            if (!first) {\n                for (const auto& seg : snapshot) {\n                    if (seg.external_waveform || !segment_has_mode(seg, mode)) continue;\n                    if (t >= seg.start_seconds && t < seg.end_seconds) {\n                        if (!first) first = &seg;\n                        else { second = &seg; break; }\n                    }\n                }\n            }\n\n            if (!first) return false;\n'''
rep(old, new)

rep('''                if (second) {\n''', '''                if (second && !first->external_waveform) {\n''')

rep('''private:\n    static bool segment_has_mode(const cache_segment& seg, stemmode::mode mode) {\n''', '''private:\n    static bool segment_has_mode(const cache_segment& seg, stemmode::mode mode) {\n''')

rep('''    void queue_job_locked(\n        double start_seconds,\n''', '''    bool range_ready_locked(stemmode::mode mode, double start_seconds, double end_seconds) const {\n        if (end_seconds <= start_seconds + 1.0e-6) return true;\n\n        double cursor = start_seconds;\n        while (cursor < end_seconds - 1.0e-6) {\n            double furthest = cursor;\n            for (const auto& seg : m_segments) {\n                if (!segment_has_mode(seg, mode)) continue;\n                if (seg.start_seconds <= cursor + 1.0e-6 &&\n                    seg.end_seconds > furthest) {\n                    furthest = seg.end_seconds;\n                }\n            }\n            if (furthest <= cursor + 1.0e-6) return false;\n            cursor = furthest;\n        }\n        return true;\n    }\n\n    void queue_job_locked(\n        double start_seconds,\n''')

rep('''    bool is_position_ready(double seconds) override {\n        return cache_manager().transport_position_ready(seconds);\n    }\n};\n''', '''    bool is_position_ready(double seconds) override {\n        return cache_manager().transport_position_ready(seconds);\n    }\n    bool publish_cache_block(\n        const char* track_path_utf8,\n        double start_seconds,\n        const float* original,\n        const float* vocals,\n        const float* instrumental,\n        t_size frames,\n        unsigned channels,\n        unsigned sample_rate) override {\n        return cache_manager().publish_external_segment(\n            local_path_from_utf8_cache(track_path_utf8),\n            start_seconds,\n            original, vocals, instrumental,\n            static_cast<size_t>(frames), channels, sample_rate);\n    }\n};\n''')

p.write_text(s, encoding='utf-8')
print('waveform PCM sharing patch applied')
